### ISSUE TITLE
Background changes to white color (BUG)

### ISSUE THREAD

**Issue by Darkensses** [react-spring/r3f-website#2]
### How to reproduce:
1. Go to [docs page](https://gracious-keller-98ef35.netlify.app/docs)
2. Click on _**Get started now!**_ link
3. We get a 404 page error (the page doesn't exist) ([Link](https://gracious-keller-98ef35.netlify.app/getting-started))
4. Hover in the link _**click here**_

### Issue
The background turns into white color in all the docs, so the font is very difficult to read.

**It's Happening on:**
Chrome 83
Firefox 77

![image](https://user-images.githubusercontent.com/23271049/85911185-3c96cc00-b7e9-11ea-9f0f-f7ae19191a44.png)
![image](https://user-images.githubusercontent.com/23271049/85911189-43254380-b7e9-11ea-9c6b-7c7a18b844dd.png)

**Comment by SaraVieira** [comment]
Hey!

I fixed the link and I am not really able to reproduce anymore in the new version here: https://5ef89ab68b766a0008ed87e2--gracious-keller-98ef35.netlify.app/

Let me know if you can still see it or if I can close the issue

Thank you!

**Comment by Darkensses** [comment]
The bug is fixed!
